### ISSUE TITLE
提示参数错误 datetime.datetime.fromtimestamp(modify_time)

### ISSUE THREAD

**Issue by gkerry** [chn-lee-yumi/MaterialSearch#42] opened 2023-11-23 14:40 UTC
环境和配置文件都确认以后. 可以成功运行. 可是只能找到一张图
点击scan后. 后台就报错
2023-11-23 22:37:11,100 werkzeug INFO 192.168.154.119 - - [23/Nov/2023 22:37:11] "GET /api/status HTTP/1.1" 200 -
Exception in thread Thread-17 (scan):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Desktop\find\MaterialSearch-main\MaterialSearch-main\scan.py", line 185, in scan
    modify_time = datetime.datetime.fromtimestamp(modify_time)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

然后就是无限期的等待. 这个scan.py我没有修改过. 有遇到相同问题的大佬吗,求指教

**Comment by chn-lee-yumi** [comment] 2023-11-24 05:29
你可以在185行前面加`print(modify_time)`看看输出吗？

**Comment by chn-lee-yumi** [comment] 2023-12-12 05:25
Hello, I tried it on Windows, and cannot reproduce your issue. Since you haven't reply for 3 weeks, I decided to close this issue. If you have any further question, please feel free to open a new one.

**Closed by chn-lee-yumi** 2023-12-12 05:25 UTC
